-- Countries table
create table countries
(
    id        bigint generated by default as identity
        primary key,
    name      varchar(255) not null,
    continent varchar(255) not null
);

-- Authors table
create table authors
(
    id         bigint generated by default as identity
        primary key,
    name       varchar(255) not null,
    surname    varchar(255) not null,
    country_id bigint references countries (id)
);

-- Books table
create table books
(
    id               bigint generated by default as identity
        primary key,
    name             varchar(255)   not null,
    category         varchar(50)    not null,
    author_id        bigint references authors (id),
    available_copies integer        not null default 0
);

-- Users table
create table users
(
    id       bigint generated by default as identity
        primary key,
    username varchar(255)   not null unique,
    password varchar(255)   not null,
    name     varchar(255)   not null,
    surname  varchar(255)   not null,
    role     varchar(50)    not null
);

-- Wishlists table
create table wishlists
(
    id           bigint generated by default as identity
        primary key,
    user_id      bigint references users (id),
    date_created timestamp,
    status       varchar(50) not null
);

-- Wishlist-Books join table (ManyToMany)
create table wishlist_books
(
    wishlist_id bigint references wishlists (id) on delete cascade,
    books_id    bigint references books (id) on delete cascade,
    primary key (wishlist_id, books_id)
);

-- Indexes for performance
create index idx_author_country on authors (country_id);
create index idx_book_author on books (author_id);
create index idx_wishlist_user_status on wishlists (user_id, status);
create index idx_user_username on users (username);
create index idx_user_role on users (role);
